//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pitanje
    {
        public int ID_Pitanje { get; set; }
        public string Ime { get; set; }
        public string Prezime { get; set; }
        public string Email { get; set; }
        public string PitanjeTekst { get; set; }
        public string Slika { get; set; }
        public bool Procitano { get; set; }
        public bool Odgovoreno { get; set; }
        public string Tag { get; set; }
        public string Komentar { get; set; }
        public Nullable<System.DateTime> DatumPitanja { get; set; }
        public Nullable<System.DateTime> DatumOdgovora { get; set; }
        public string Odgovor { get; set; }
    }
}
