//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model.Field
{
    
     public enum Pitanje 
     {	
    	ID_Pitanje,
    	Ime,
    	Prezime,
    	Email,
    	PitanjeTekst,
    	Slika,
    	Procitano,
    	Odgovoreno,
    	Tag,
    	Komentar,
    	DatumPitanja,
    	DatumOdgovora,
    	Odgovor,
    }   
}
