//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model.Field
{
    
     public enum webpages_Membership 
     {	
    	UserId,
    	CreateDate,
    	ConfirmationToken,
    	IsConfirmed,
    	LastPasswordFailureDate,
    	PasswordFailuresSinceLastSuccess,
    	Password,
    	PasswordChangedDate,
    	PasswordSalt,
    	PasswordVerificationToken,
    	PasswordVerificationTokenExpirationDate,
    }   
}
